version: "3"

services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379"

  dynamodb-test:
    build:
      context: .
      dockerfile: docker/dynamodb/Dockerfile
    command: -jar DynamoDBLocal.jar --inMemory
    ports:
      - "8002:8000"

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/task
    environment: &environment
      - ALFRED_REDIS_HOST=redis
      - AWS_ACCESS_KEY_ID=aws_access_key
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=aws_access_secret
      - DYNAMODB_HOST=http://dynamodb-test:8000
      - DYNAMODB_PREFIX=alfred
    ports:
      - "8108:8108"
    depends_on:
      - "redis"
      - "dynamodb-test"
volumes:
  redis-data:
